### ISSUE TITLE
Endre tekst til svar innen 48 timer

### ISSUE THREAD

**Issue by vavaen** [telemark/skoleskyss-arbeid#11]
Endre tekst på side 4 i søknadsskjema til: Du vil innen 48 timer få kvittering og svar på din søknad. Dette leser du ved å logge deg inn i din Altinn-postkasse. Om du ikke leser svaret i Altinn, sender vi svarbrevet hjem til deg.

**Comment by zrrrzzt** [comment]
Kan jeg foreslå følgende tekst i stedet?

```
Innen 48 timer får du kvittering og svar på søknaden i Altinn-postkassen din.
Leser du ikke svaret der, blir alt sendt hjem til deg.
```

Hva tenker du @vavaen ?

**Comment by zrrrzzt** [comment]
Fixed og ute i det fri

**Comment by vavaen** [comment]
:+1:
