### ISSUE TITLE
Delt bosted

### ISSUE THREAD

**Issue by vavaen** [telemark/skoleskyss-arbeid#13]
Ny logikk:
- Hvis folkeregisteradressen er over 6,5 km er det greit med automatisk tilslag.
  Men hvis folkeregisteradressen er under grensekravet, og det er satt opp en annen adresse over så trenger vi dokumentasjon. 
- Når Delt bosted, og avstand begge adresser under 5,5 – skal det gis avslag

**Comment by zrrrzzt** [comment]
Flyttet til rett repo: https://github.com/telemark/tfk-saksbehandling-skoleskyss/issues/11
