### ISSUE TITLE
Undefined i adressefeltet

### ISSUE THREAD

**Issue by vavaen** [telemark/skoleskyss-arbeid#14]
Når ikke gateadresse, kommer det automatisk skrevet Undefined i feltet - deretter postnr og poststed. Det er ønskelig å ha feltet blankt.
Fra Geir: 
Undefined er JavaScriptsk for "finnes ikke".

Det er en enkel endring som må til @Jonas.

Linje 51 i denne https://github.com/telemark/tfk-saksbehandling-skoleskyss/blob/master/lib/lookupDSF.js kan endres fra 

street: item.dsfData.ADR,

til

street: item.dsfData.ADR || '',

**Comment by zrrrzzt** [comment]
Denne mener jeg faktisk @maccyber løste og dyttet ut tidligere i uken
