### ISSUE TITLE
Korrigere felt for Postnr og Poststed i maler

### ISSUE THREAD

**Issue by vavaen** [telemark/skoleskyss-arbeid#8]
Postnr og poststed havner feil i kvitterings/foreløpig svar og vedtaksmalene, de havner på samme linje som gateadresse. Postnr og poststed skal på linjen under

**Comment by maccyber** [comment]
Screenshot fra test.

![adr](https://cloud.githubusercontent.com/assets/701351/8192093/2cbfd040-146c-11e5-86e5-ebeaca814df6.png)

**Comment by vavaen** [comment]
Yess!! Der er den på plass. Lekkert ☺
Mvh Vanja

Fra: Jonas Enge [mailto:notifications@github.com]
Sendt: 16. juni 2015 21:11
Til: telemark/skoleskyss-arbeid
Kopi: Vanja Valjord Christensen
Emne: Re: [skoleskyss-arbeid] Korrigere felt for Postnr og Poststed i maler (#8)

[adr]https://cloud.githubusercontent.com/assets/701351/8192093/2cbfd040-146c-11e5-86e5-ebeaca814df6.pngScreenshot fra test.
