### ISSUE TITLE
Oppgradere til siste versjoner av iojs og MongoDB

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/skoleskyss-arbeid#9]
Foreslår at vi oppgraderer server med iojs 2.3.0 og MongoDB 3.0.4. Etter oppgradering lar vi disse versjonene leve til etter rushet i august.

**Comment by maccyber** [comment]
Enig. Gjør dette i kveld.

**Comment by maccyber** [comment]
Oppdatert til iojs v2.3.0, mongo 3.0.4 og annet.
